embed_assets: on
package_assets: always

javascripts:
  transformer_informations:
    - public/javascripts/jquery-1.4.2.min.js
    - public/javascripts/jquery-ui-1.8.4.custom.min.js
    - public/javascripts/jquery.blockUI.js
    - public/javascripts/jquery.tmpl.js
    - public/javascripts/facebox.js
    - public/javascripts/jquery.url.js
    - public/javascripts/jquery.tablesorter.min.js
    - public/javascripts/jquery.cluetip.js
  transformer_informations_index:
    - public/javascripts/jquery.flot.min.js
    - public/javascripts/jquery.flot.selection.min.js    
    - public/javascripts/jquery.flot.axislabels.js
    - public/javascripts/jquery.multirowcheckboxmenu.js    
    - public/javascripts/controllers/transformer_informations.js    
    
stylesheets:
  transformer_informations:
    - public/stylesheets/960.css
    - public/stylesheets/template.css
    - public/stylesheets/nav.css
    - public/stylesheets/colour.css
    - public/stylesheets/facebox.css
    - public/stylesheets/jquery-ui-1.8.4.custom.css
    - public/stylesheets/jquery.cluetip.css
    - public/stylesheets/controllers/transformer_information.css
    